info:
  app:
    name: Balada API Gateway
    description: Balada API Gateway - Desenvolvimento
    version: '@project.version@'


url:
  bld-api-gateway: http://localhost:8080

server:
  port:8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://setedevsdbdev.cloudns.ph:5432/bldbdev01
    username: postgres
    password: Postgres@2021
    type: com.zaxxer.hikari.HikariDataSource
